@echo off
echo Starting MarxSimplified development server...
start cmd /k "npm run dev"
echo Waiting for server to initialize...
timeout /t 3 >nul
echo Opening browser...
start http://localhost:5173/
echo Done!
