import type { GlossaryTerm } from './types';

export const classicalTerms: GlossaryTerm[] = [
  {
    "term": "Bourgeoisie",
    "pattern": "bourgeoisie|bourgeois|bourgeoise",
    "definition": "The class of people in society who own the businesses, factories, land, and machinery that generate wealth. They survive by employing workers to run their assets.",
    "misconception": "Anyone who is wealthy or middle-class. In reality, a high-earning office worker is still not part of the bourgeoisie unless they own businesses that generate passive income from other people's work.",
    "dayToDayExample": "A tech billionaire or real estate developer who earns income from the profits generated by employees or tenants, without needing to perform manual shift work.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Proletariat",
    "pattern": "proletariat|proletarians|proletarian",
    "definition": "The modern working class. This includes anyone who must sell their time and ability to work (labor-power) for a wage or salary to survive, because they do not own businesses or land.",
    "misconception": "Only manual laborers or people working in industrial factories. Today, office staff, retail workers, teachers, nurse assistants, and software developers are all part of the proletariat because they survive on wages.",
    "dayToDayExample": "A nurse, teacher, retail worker, or software developer who must sell their time for a paycheck because they do not own a company or land.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Private Property",
    "pattern": "private property",
    "definition": "Productive assets that make money by employing other people's labor (like factories, machinery, office buildings, or rental properties).",
    "misconception": "Your personal belongings (like your clothes, car, phone, or the house you live in). Marxism does not want to take away your personal items: it only wants to end the private ownership of businesses that exploit other people's labor.",
    "dayToDayExample": "A corporate warehouse or apartment complex owned to extract revenue, as opposed to personal belongings like your phone, clothes, or car.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Means of Production",
    "pattern": "means of production",
    "definition": "The physical tools, land, raw materials, and factories required to produce goods and services.",
    "misconception": "The final products themselves (like a phone or a loaf of bread). The means of production are the factories and farms used to make them, which socialists believe should be owned collectively by society rather than by private owners.",
    "dayToDayExample": "The heavy machinery in a car factory or the server farms used by cloud computing platforms to generate commercial products.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Commodity",
    "pattern": "commodity|commodities",
    "definition": "A good or service produced specifically for the purpose of selling it in the market to make a profit, rather than for direct personal use.",
    "misconception": "Any useful object. A coat you sew for yourself is a useful object; it only becomes a commodity when it is manufactured in a factory to be sold in stores.",
    "dayToDayExample": "A coat produced in a factory specifically to be shipped and sold in retail stores for profit.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Commodity Fetishism",
    "pattern": "commodity fetishism|fetishism of commodities",
    "definition": "The illusion under capitalism where social relationships between human beings appear as economic relationships between inanimate objects and money prices.",
    "misconception": "An unhealthy obsession with luxury brands. Commodity fetishism means treating a price tag or product as having inherent magical value, obscuring the human labor and working conditions that created it.",
    "dayToDayExample": "Buying a designer shirt for $150 and viewing it as a symbol of status, while remaining unaware of the factory workers who stitched it.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Labor-Power",
    "pattern": "labor-power|labour-power|labor power|labour power",
    "definition": "A worker's capacity to work: their time, physical energy, and mental focus.",
    "misconception": "The work itself, or the value of the final product. Capitalists do not buy your completed products; they buy your time and energy (labor-power) for a shift, and then they own everything you produce during those hours.",
    "dayToDayExample": "Working an eight-hour shift at a coffee shop, where you trade your physical energy and focus for a fixed hourly wage.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Capital",
    "pattern": "capital",
    "definition": "Wealth (money, equipment, or properties) that is invested to make more wealth through the employment of wage labor.",
    "misconception": "Just savings or cash. Money only becomes capital when it is actively used to buy assets and hire workers to generate profit.",
    "dayToDayExample": "An investor purchasing fleet vehicles and equipment to hire workers and launch a profit-generating logistics business.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Class Struggle",
    "pattern": "class struggle|class struggles",
    "definition": "The built-in conflict of interest between those who own the businesses and those who work for them.",
    "misconception": "Personal hatred or violent riots. Class struggle is an objective economic reality: employers naturally want to keep wages low and hours high to increase profits, while workers want higher wages and shorter hours.",
    "dayToDayExample": "Warehouse workers bargaining for safer working conditions and higher wages while management seeks to cut operating costs.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Class Enemy",
    "pattern": "class enemy|class enemies",
    "definition": "In Marxist political analysis, an individual, organization, or social group whose objective economic interests and social role stand in direct structural opposition to the working class and the construction of socialism.",
    "misconception": "A personal hatred or moral insult against individual people. Class enemy describes an objective socioeconomic role: those who own private capital, exploit labor, or actively enforce ruling-class dominance against working-class liberation.",
    "dayToDayExample": "Monopoly capitalists who use private wealth to lobby for wage cuts, outlaw labor unions, and fund corporate political campaigns.",
    "theoryTags": ["Classical Marxism", "Marxism-Leninism"]
  },
  {
    "term": "Class Traitor",
    "pattern": "class traitor|class traitors|traitor to their class",
    "definition": "An individual who acts against the political or economic interests of their own social class: either a working-class individual who aids capitalist exploitation (such as a strike-breaker or police officer) or a bourgeois individual who defects to support the working class (such as Friedrich Engels).",
    "misconception": "That class origin permanently dictates a person's political allegiance. Individuals can choose to betray their class interests; Marx and Engels were born into wealthy families but committed themselves entirely to working-class revolution.",
    "dayToDayExample": "A factory worker accepting extra pay to act as a scab breaking a union strike (working-class traitor) or a wealthy heir donating their fortune to fund revolutionary labor organizing (bourgeois traitor).",
    "theoryTags": ["Classical Marxism", "Marxism-Leninism"]
  },
  {
    "term": "Class Reconciliation",
    "pattern": "class reconciliation|reconciliation of classes|harmonizing class interests",
    "definition": "The reformist or social-democratic ideology claiming that the fundamental contradictions between capital and labor can be permanently eliminated through state arbitration, welfare regulations, and peaceful negotiation without abolishing private property.",
    "misconception": "That capital and labor share identical long-term interests. Lenin demonstrated in 'State and Revolution' that the state arises precisely because class contradictions are irreconcilable.",
    "dayToDayExample": "Government arbitration boards setting maximum wage caps to keep businesses profitable while asking workers to accept sacrifices for national economic health.",
    "theoryTags": ["Classical Marxism", "Marxism-Leninism"]
  },
  {
    "term": "Surplus Value",
    "pattern": "surplus value|surplus-value",
    "definition": "The extra value created by workers above the cost of their own wages. This unpaid labor is the source of all capitalist profit.",
    "misconception": "Just the markup price of a commodity. It is actually the difference between the total value the worker produces and the wage they receive.",
    "dayToDayExample": "A worker creating $200 worth of merchandise during a shift while receiving $20 an hour in wages, leaving the remaining profit with the business owner.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Exploitation",
    "pattern": "exploitation|exploited|exploits",
    "definition": "The process where capitalists extract surplus value from the unpaid labor of workers, paying them less than the value they produce.",
    "misconception": "Only occurring under extremely bad working conditions or abusive bosses. For Marxists, exploitation is an objective, mathematical reality of all wage labor: even well-paid software developers are exploited if they produce more value than their salary.",
    "dayToDayExample": "A software developer earning a fixed annual salary while their code generates millions of dollars in recurring subscription profits for company shareholders.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Alienation",
    "pattern": "alienation|alienated",
    "definition": "The feeling of separation and lack of control that workers experience under capitalism: separation from the product of their labor, from the act of production, from their fellow workers, and from their human potential.",
    "misconception": "Simply feeling lonely or sad. It is an objective condition caused by workers having no control over their daily labor or what happens to the products they make.",
    "dayToDayExample": "An assembly line worker who installs car doors all day but cannot afford to purchase the car they help build, feeling disconnected from their daily labor.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Use-Value",
    "pattern": "use-value|use value|use-values|use values",
    "definition": "The practical utility of a commodity: how it satisfies a human need or desire (like a coat keeping you warm).",
    "misconception": "The price of an item. Use-value is qualitative, while price or exchange-value is quantitative. A glass of water has immense use-value for survival but usually has very little exchange-value.",
    "dayToDayExample": "A warm winter jacket keeping you dry and insulated during cold weather.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Exchange-Value",
    "pattern": "exchange-value|exchange value|exchange-values|exchange values",
    "definition": "The proportion in which a commodity exchanges for other commodities, which under capitalism is expressed as a money price.",
    "misconception": "The same as use-value. An object can have high use-value but no exchange-value (like air or home-cooked meals), or high exchange-value but little use-value (like a diamond).",
    "dayToDayExample": "A smartphone listed in a store for $999 or traded for three months of grocery purchases.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Class Interest",
    "pattern": "class interest|class interests",
    "definition": "The shared economic and political goals that arise from a group's position in the system of production. The bourgeoisie's class interest is to maximize profits and protect private property; the proletariat's class interest is to improve wages, conditions, and ultimately to collectively own the means of production.",
    "misconception": "Individual personal preferences or opinions. Class interest is not about what a single person wants; it is the objective set of economic goals that benefit an entire class, whether or not individual members are aware of them.",
    "dayToDayExample": "Workers pushing for strong public healthcare funded by corporate taxes, while corporate leaders lobby for tax reductions to boost dividends.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Capitalism",
    "pattern": "capitalism|capitalistic",
    "definition": "An economic system and social order where the means of production (factories, land, technology) are privately owned, and economic activity is driven by market competition and profit extraction using wage labor.",
    "misconception": "That capitalism simply means trade or buying goods in a market. Markets existed for thousands of years before capitalism; capitalism specifically refers to a total mode of production dominated by private corporate ownership and generalized wage labor.",
    "dayToDayExample": "A society where healthcare, housing, food, and utilities are owned by private corporations operating to generate profit for shareholders.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Capitalist",
    "pattern": "capitalist|capitalists",
    "definition": "An individual member of the bourgeoisie who owns private productive property and lives primarily off the profits, dividends, or interest extracted from the labor of employed workers.",
    "misconception": "Anyone who supports free markets or works a high-earning corporate job. A capitalist specifically belongs to the class that owns productive assets and buys other people's labor-power.",
    "dayToDayExample": "A corporate investor or venture capitalist who earns income by purchasing shares in companies run by hired employees.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Communism",
    "pattern": "communism",
    "definition": "A stateless, classless, moneyless socio-economic system where the means of production are owned collectively by society, and production is organized to directly satisfy human needs ('from each according to their ability, to each according to their need').",
    "misconception": "That communism means total state bureaucracy control. In Marxist theory, full communism is the phase after the state has withered away because class antagonisms no longer exist.",
    "dayToDayExample": "A society where all basic necessities like food, housing, healthcare, and education are produced collectively and accessed freely by everyone without money or prices.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Communist",
    "pattern": "communist|communists|communist party",
    "definition": "An individual or political organization dedicated to the theoretical principles of scientific socialism and the practical struggle to abolish capitalism and build a communist society.",
    "misconception": "A government official who favors high taxes. A communist specifically advocates for replacing private corporate ownership with collective working-class ownership of the economy.",
    "dayToDayExample": "A political activist organizing workers to conquer political power and build democratic public control over production.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Socialism",
    "pattern": "socialism|socialistic",
    "definition": "The transitional lower phase of communist society following the overthrow of capitalism, where the working class holds political power and collectively owns major industries ('from each according to their ability, to each according to their contribution').",
    "misconception": "Just government welfare programs or social democracy in a capitalist country. True socialism requires replacing private corporate ownership of major industries with public worker ownership.",
    "dayToDayExample": "An economy where key industries (energy, housing, healthcare, transit) are publicly owned and democratically planned by society.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Socialist",
    "pattern": "socialist|socialists",
    "definition": "An individual or movement advocating for the social ownership of the means of production and the democratic organization of economic life by working people.",
    "misconception": "Someone who wants the government to control every detail of personal life. Socialists seek democratic control over productive wealth so that individuals can flourish freely.",
    "dayToDayExample": "A union organizer campaigning to convert a corporate factory into a democratically worker-managed cooperative.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Petty Bourgeoisie",
    "pattern": "petty-bourgeoisie|petty bourgeoisie|petite-bourgeoisie|petite bourgeoisie|petit-bourgeoisie|petit bourgeoisie|petty-bourgeoisies|petty bourgeoisies|petite-bourgeoisies|petite bourgeoisies|petty-bourgeois|petty bourgeois|petite-bourgeois|petite bourgeois|petit-bourgeois|petit bourgeois|small-bourgeoisie|small-bourgeoisies|small-bourgeois",
    "definition": "The social class of small business owners, self-employed proprietors, independent contractors, and shopkeepers who own some productive property but must also work themselves.",
    "misconception": "Regular office employees who make good salaries. The petty bourgeoisie specifically owns small-scale productive assets, placing them in an unstable position between big business owners and wage workers.",
    "dayToDayExample": "An independent bakery owner who works behind the counter every day alongside two hired employees.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Class Consciousness",
    "pattern": "class consciousness|class conscious|class-conscious",
    "definition": "The awareness by a social class (especially the working class) of its distinct economic position, collective interests, and historical role in changing society.",
    "misconception": "Just knowing what job you have. Class consciousness means recognizing that workers share common political and economic interests against capital, regardless of individual occupation or background.",
    "dayToDayExample": "Workers across different departments and companies banding together in a unified union drive because they recognize their shared economic plight.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "False Consciousness",
    "pattern": "false consciousness",
    "definition": "A state of mind in which members of an exploited class hold beliefs and values that misinterpret their real economic situation and actively work against their own class interests.",
    "misconception": "Being unintelligent or foolish. False consciousness is the result of pervasive ideological messaging from dominant cultural and media institutions that frame corporate interests as general public interests.",
    "dayToDayExample": "A low-wage worker opposing workplace safety regulations or healthcare access because corporate media convinced them it harms business leaders.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Base and Superstructure",
    "pattern": "base and superstructure|economic base|superstructure",
    "definition": "A Marxist way of describing the relationship between how a society organizes its economic life and the institutions and ideas that develop around it. The 'base' is how people produce, own, and distribute things; the 'superstructure' includes laws, politics, education, media, religion, and culture. The idea is that the way a society organizes its economy strongly influences these institutions, while those institutions can also help maintain the existing economic system.",
    "misconception": "That Marxism says economics automatically determines everything else. The argument is more that economic arrangements create pressures and incentives that shape institutions, ideas, and cultural norms, which can in turn reinforce or challenge those arrangements.",
    "dayToDayExample": "In a society where businesses and private property are central to the economy, laws and political institutions are likely to place a strong emphasis on protecting contracts, property rights, and commercial activity. Those laws then help keep that economic system functioning.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Mode of Production",
    "pattern": "mode of production|modes of production",
    "definition": "The overall structure of an economic system, combining the productive forces (tools, land, labor) and the social relations of production (ownership and class relations).",
    "misconception": "Just the technology or manufacturing technique used in a factory. A mode of production encompasses the entire socio-economic order, such as feudalism, capitalism, or socialism.",
    "dayToDayExample": "Capitalism as a total system where market exchange, wage labor, and private ownership dictate how goods are made and distributed.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Relations of Production",
    "pattern": "relations of production|social relations of production|relation of production",
    "definition": "The social relationships people must enter into to produce goods, specifically defined by who owns the property, tools, and resources, and who performs the work.",
    "misconception": "Friendly personal relationships between co-workers. Relations of production are structural class relationships, such as landlord-tenant, master-serf, or employer-employee.",
    "dayToDayExample": "The legal and economic contract between a corporate employer who owns the office equipment and an employee who performs work for an hourly wage.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Forces of Production",
    "pattern": "forces of production|productive forces|force of production|productive force",
    "definition": "The combination of human labor skill and knowledge with the technical means of production (tools, machinery, raw materials, and scientific technology).",
    "misconception": "Just physical machinery. Productive forces include worker knowledge, organization, scientific advances, and natural resources.",
    "dayToDayExample": "Automated robotics combined with skilled software design and raw steel to manufacture electric vehicles at scale.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Value",
    "pattern": "value of a commodity|labor theory of value|law of value|value",
    "definition": "In Marxist economics, the amount of socially necessary labor time embodied within a commodity, which regulates its exchange proportion in the market.",
    "misconception": "Value being purely subjective based on individual desire. While individual desire creates utility (use-value), economic value is rooted objectively in the average socially necessary labor time needed to produce the item.",
    "dayToDayExample": "A hand-crafted wooden table having higher economic value than a plastic cup because it requires significantly more average labor time to produce.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Abstract Labor",
    "pattern": "abstract labor|abstract labour",
    "definition": "Human labor expenditure considered in general, stripped of its specific concrete form (whether tailoring, weaving, or coding). Abstract labor is the substance of economic value in commodity production.",
    "misconception": "That abstract labor is a purely mental concept. It is a real social equalization that occurs in market exchange when different tasks are measured against money.",
    "dayToDayExample": "A coat and a chair being priced equally in a market because both represent an equal quantity of average human labor time.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Concrete Labor",
    "pattern": "concrete labor|concrete labour",
    "definition": "Specific, useful human work performed in a particular form (such as carpentry, farming, or software engineering) that satisfies a specific human need and creates use-value.",
    "misconception": "That concrete labor directly creates market price. Concrete labor creates useful objects (use-values); it is abstract labor that creates exchange value.",
    "dayToDayExample": "A carpenter cutting, sanding, and assembling wood into a comfortable chair.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Necessary Labor",
    "pattern": "necessary labor|necessary labour",
    "definition": "The portion of the working day during which the worker produces value equal to the cost of their own wages and subsistence.",
    "misconception": "That workers spend their entire shift producing their own wages. Necessary labor takes up only a fraction of the workday; the remainder is surplus labor.",
    "dayToDayExample": "A factory worker earning $120 a day who produces $120 worth of shoes in the first 3 hours of an 8-hour shift.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Surplus Labor",
    "pattern": "surplus labor|surplus labour",
    "definition": "The additional unpaid labor time worked beyond necessary labor during which the worker creates surplus value appropriated by the capitalist owner.",
    "misconception": "That surplus labor is overtime work. Surplus labor occurs during regular shift hours whenever value is generated above wage costs.",
    "dayToDayExample": "Working the remaining 5 hours of an 8-hour shift after reproducing daily wage costs, creating net profit for corporate owners.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Constant Capital",
    "pattern": "constant capital",
    "definition": "The portion of capital invested in non-human means of production (machinery, factory buildings, raw materials) whose existing value is transferred unchanged to the final product during production.",
    "misconception": "That constant capital generates new profit on its own. Machinery only adds its existing purchase value to products bit by bit as it wears down.",
    "dayToDayExample": "A coffee shop owner buying espresso machines and coffee beans, which transfer their cost directly into brewed coffee cups.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Variable Capital",
    "pattern": "variable capital",
    "definition": "The portion of capital invested in purchasing human labor-power (wages), which reproduces its own value and creates new surplus value during the production process.",
    "misconception": "That variable capital is just another business expense. It is called variable because human labor alters value, expanding total wealth beyond initial wage investment.",
    "dayToDayExample": "Hiring a barista for $15 an hour who uses equipment to brew $100 worth of drinks in that same hour.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Fixed Capital",
    "pattern": "fixed capital",
    "definition": "Instruments of labor (machinery, factory buildings, tools, infrastructure) that remain fixed in the production process and transfer their value to products gradually over many production cycles.",
    "misconception": "That fixed capital remains valuable forever. It undergoes physical wear and tear as well as moral obsolescence when newer technology emerges.",
    "dayToDayExample": "A commercial printing press used over ten years to print millions of books before requiring total replacement.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Circulating Capital",
    "pattern": "circulating capital",
    "definition": "Capital invested in raw materials, auxiliary materials, and labor wages that is completely consumed within a single production cycle and must be replaced out of product sales.",
    "misconception": "That circulating capital is cash floating in bank accounts. Circulating capital is material inputs and wages turned over entirely per production run.",
    "dayToDayExample": "The flour, yeast, electricity, and daily baker wages consumed in baking today's loaf batches.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Accumulation of Capital",
    "pattern": "accumulation of capital|capital accumulation|accumulation",
    "definition": "The continuous reinvestment of surplus value (profits) back into buying additional means of production and hiring more labor to expand business scale and generate future profits.",
    "misconception": "Capitalists hoarding cash in a bank account. True capital accumulation requires constantly plowing profits back into expanding business operations.",
    "dayToDayExample": "A retail company taking yearly corporate profits to build ten new store locations and hire hundreds of additional staff.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Primitive Accumulation",
    "pattern": "primitive accumulation of capital|primitive accumulation",
    "definition": "The historical process that created the foundations of capitalism by forcibly separating peasants and indigenous peoples from their land, transforming them into landless wage workers.",
    "misconception": "That early capitalists accumulated their initial wealth solely through hard work and thrift. Historical primitive accumulation relied on land seizures, enclosures, colonialism, and transatlantic slavery.",
    "dayToDayExample": "18th-century parliamentary enclosure acts in Britain fencing off common grazing lands, forcing displaced peasants into urban factory wage labor.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Reproduction of Capital",
    "pattern": "reproduction of capital|simple reproduction",
    "definition": "The process by which capitalist production continuously renews its economic conditions. Simple reproduction maintains production at the same scale without expanding capital investment.",
    "misconception": "That an economic system stays alive automatically. Capitalism must continuously reproduce worker dependency on wages and capital ownership of property every single cycle.",
    "dayToDayExample": "A small repair shop using monthly revenue to restock spare parts and pay rent while maintaining the exact same business size.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Expanded Reproduction",
    "pattern": "expanded reproduction",
    "definition": "The process where a portion of surplus value is converted into new capital, continually scaling up production, equipment, and employed workforce over time.",
    "misconception": "That business expansion is optional under capitalism. Competitive pressure obliges capital to continually pursue expanded reproduction to avoid market defeat.",
    "dayToDayExample": "A tech company investing 40% of annual profits into new data centers and hiring 200 software engineers.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Crisis of Overproduction",
    "pattern": "crisis of overproduction|crises of overproduction|overproduction",
    "definition": "A recurring capitalist crisis where more goods are produced than can be sold at a profit, not because human need is satisfied, but because workers lack the purchasing power to buy them.",
    "misconception": "A shortage of goods. Capitalism uniquely suffers from crises of abundance, where factories close and goods rot while people suffer from lack of access.",
    "dayToDayExample": "Farmers dumping milk and letting crops rot during an economic downturn while food-insecure families cannot afford store prices.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Reserve Army of Labour",
    "pattern": "industrial reserve army|reserve army of labor|reserve army of labour|relative surplus population|surplus population|reserve army",
    "definition": "The pool of unemployed or underemployed workers under capitalism that keeps wages in check by providing a constant threat of worker replacement.",
    "misconception": "Unemployment being an accidental failure of capitalism. A reserve army of labor is structurally necessary for capitalism to discipline working-class wage demands and force workers to accept low pay.",
    "dayToDayExample": "Job listings receiving hundreds of desperate applications, which employers leverage to deny wage increases to current staff.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Relative Surplus Population",
    "pattern": "floating surplus population|latent surplus population|stagnant surplus population|forms of surplus population",
    "definition": "The three distinct forms of the industrial reserve army identified by Marx in Capital Vol. 1: 'Floating' (workers hired and fired as economic cycles fluctuate), 'Latent' (rural agricultural laborers displaced by industrial farming waiting to move to cities), and 'Stagnant' (workers with extremely irregular, poorly paid employment surviving on the margins of the formal labor market).",
    "misconception": "That all unemployed workers are identical. Capital constantly shifts workers between these three tiers depending on technological changes, agricultural mechanization, and market demand.",
    "dayToDayExample": "Factory workers laid off during a recession (floating), rural farm hands moving to urban areas for warehouse work (latent), and informal day laborers or temp workers (stagnant).",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Pauperism",
    "pattern": "pauperism|pauper|paupers|absolute impoverishment",
    "definition": "The lowest sediment of the relative surplus population in Marx's analysis: individuals who have been permanently broken, injured, or cast out of the active labor process due to industrial accidents, extreme age, sickness, or prolonged structural unemployment.",
    "misconception": "A personal moral defect. Marx demonstrated that pauperism is the inevitable product of capitalist accumulation: as wealth accumulates at one pole, pauperism and misery accumulate at the opposite pole.",
    "dayToDayExample": "Permanently disabled factory workers receiving no state support or workers rendered obsolete by automation leaving them without any source of livelihood.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Precariat",
    "pattern": "precariat|precarious proletariat",
    "definition": "A contemporary term (coined by Guy Standing and analyzed by Post-Marxists) describing a growing social class of workers characterized by insecure gig employment, zero-hour contracts, lack of labor rights, and absence of occupational identity.",
    "misconception": "A completely separate non-working class. Classical Marxists point out that the precariat is a modern form of Marx's stagnant surplus population operating under neoliberal deregulation.",
    "dayToDayExample": "Rideshare drivers and app-based delivery workers taking on multiple gig contracts without health benefits, paid leave, or job security.",
    "theoryTags": ["Classical Marxism", "Neo-Marxism"]
  },
  {
    "term": "Labor-Power Obsolescence",
    "pattern": "labor-power obsolescence|labour-power obsolescence|technological displacement|technological unemployment",
    "definition": "The process in capitalist accumulation where technological advances (automation, machinery, AI) devalue or eliminate entire categories of human labor-power, casting skilled workers into the reserve army of labor.",
    "misconception": "Technological progress benefiting all workers equally. Under capitalism, labor-saving machinery is owned by capitalists, turning technological progress into a tool for displacing workers and lowering wages.",
    "dayToDayExample": "Self-checkout kiosks replacing retail cashiers or automated software displacing data-entry clerks, forcing displaced workers to compete for lower-paying jobs.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Lumpenproletariat",
    "pattern": "lumpenproletariat|lumpen",
    "definition": "A Marxist term for people on the margins of the regular working economy and outside organized wage labor, often including people involved in begging, petty crime, hustling, or other irregular forms of survival. Marx and later Marxists generally viewed this group as lacking the collective organization and class interests associated with the working class, making it easier for powerful political forces to recruit or manipulate them.",
    "misconception": "That the lumpenproletariat simply means poor people, unemployed people, homeless people, disabled people, or anyone without a stable job. None of these circumstances automatically makes someone lumpenproletarian. Marx sometimes included vagrants and other people living outside regular employment among the lumpenproletariat, but the concept is more specifically about being detached from regular production and organized working-class life. A homeless person can be a worker, a disabled person can be a worker, and an unemployed person can remain part of the working class even when they are temporarily or permanently unable to find work. Sometimes lumpen can be used as an insult by some people - that is not the intended usage of the term.",
    "dayToDayExample": "A criminal gang, street hustlers, et cetera - operating outside regular employment and organized labor could be described as lumpenproletarian. Historically, Marxists have also used the term for people surviving through irregular or marginal activities, including some people described as vagrants. The important distinction is that homelessness, disability, or poverty by themselves are not what defines the category.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Lumpenbourgeoisie",
    "pattern": "lumpenbourgeoisie|lumpen bourgeoisie",
    "definition": "A Marxist term, especially associated with later Marxist and dependency-theory writing, for a section of the wealthy or business class whose position depends on parasitic, extractive, or externally dependent forms of wealth rather than developing productive industry. The term is often used for local elites who make money by acting as intermediaries for foreign capital or by profiting from activities such as speculation, resource extraction, corruption, or organized crime.",
    "misconception": "That it simply means corrupt, greedy, criminal, or unpopular rich people. The point is not that a wealthy person is personally immoral, but that their economic position is seen as dependent on extracting wealth, controlling access, or serving more powerful economic interests rather than building an independent productive economy. A mafia boss, for example, might be described as lumpenbourgeois in some Marxist analyses because they accumulate substantial wealth through organized extraction, protection, trafficking, and control rather than through ordinary productive investment.",
    "dayToDayExample": "A mafia organization that controls businesses, extorts local firms, launders money, and uses political connections to capture wealth could be described as a lumpenbourgeois formation. In a different context, a wealthy local elite that becomes rich by acting as an intermediary for foreign corporations (such as securing access to land or natural resources while taking a share of the profits) could also be described as lumpenbourgeois. The common idea is an elite that accumulates wealth through extraction, brokerage, or dependence rather than developing productive capacity on its own.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Wage Labor",
    "pattern": "wage labor|wage labour|wage slavery|wage-labor|wage-labour",
    "definition": "The socio-economic relationship where workers, lacking their own means of production, sell their labor-power to capitalists in exchange for a money wage.",
    "misconception": "That wage labor is a free voluntary transaction between equals. In reality, because workers must buy food and shelter to survive, selling labor-power under capitalism is an economic necessity.",
    "dayToDayExample": "Working an 8-hour shift at a retail store for an hourly wage, where your employer owns the store, inventory, and profits.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Proletarianization",
    "pattern": "proletarianization|proletarianisation|proletarianized|proletarianised",
    "definition": "The historical and ongoing economic process by which self-employed artisans, independent farmers, small proprietors, or middle-class professionals are stripped of independent property and turned into wage-dependent proletarians.",
    "misconception": "That class status is fixed or static. Proletarianization shows how capitalist competition constantly pushes former independent producers into the ranks of wage labor.",
    "dayToDayExample": "An independent family farmer losing their land due to corporate agribusiness debt and taking a job as an hourly factory worker.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Commodification",
    "pattern": "commodification|commodified|commodifying|commodify",
    "definition": "The transformation of goods, services, ideas, nature, or human relationships into marketable commodities to be bought and sold for profit.",
    "misconception": "That everything has always been for sale. Commodification is the historical expansion of market logic into areas like healthcare, housing, water, and education.",
    "dayToDayExample": "Turning municipal drinking water or healthcare access into expensive commercial subscriptions sold by private corporations.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Ideology",
    "pattern": "ideology|ideologies|ideological",
    "definition": "The system of ideas, representations, and cultural beliefs through which human beings make sense of their social existence and world.",
    "misconception": "That ideology only refers to political extremism. Everyone lives within ideology, which shapes common sense assumptions about everyday life.",
    "dayToDayExample": "Viewing competitive behavior as inherent human nature rather than a habit learned in market societies.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Ruling-Class Ideology",
    "pattern": "ruling-class ideology|ruling class ideology",
    "definition": "The specific framework of ideas and assumptions that justifies the existing social order, presenting the economic interests of the dominant capitalist class as universal common sense.",
    "misconception": "That public opinions are formed randomly. The ruling-class ideology dominates because the class controlling material production also controls intellectual production.",
    "dayToDayExample": "The popular belief that extreme wealth inequality is a natural result of individual talent and effort rather than property ownership.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Cultural Hegemony",
    "pattern": "cultural hegemony|hegemony|hegemonic",
    "definition": "The leadership or dominance of a ruling class achieved by shaping cultural values, morals, and common sense so that subordinate classes accept the status quo voluntarily.",
    "misconception": "Dominance maintained purely through military control. Hegemony operates through media, education, and culture to make capitalist values seem like universal human values.",
    "dayToDayExample": "Working-class people taking pride in corporate competition and viewing strikes as disruptive nuisances.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Social Reproduction",
    "pattern": "social reproduction",
    "definition": "The total social process through which working-class life, labor-power, and society's overall class structure are sustained, renewed, and maintained from one generation to the next.",
    "misconception": "That production in factories is the only part of the economy that matters. Social reproduction highlights how non-factory domestic, caregiving, and community work make capitalist production possible.",
    "dayToDayExample": "Providing public housing, healthcare, schooling, and community care so that current and future generations of workers remain healthy and capable of labor.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Reproductive Labor",
    "pattern": "reproductive labor|reproductive labour",
    "definition": "The specific physical, emotional, and domestic work (cooking, cleaning, childcare, eldercare) required to maintain current workers daily and raise future workers.",
    "misconception": "That domestic chores are merely personal favors or non-economic activity. Reproductive labor reproduces labor-power, the fundamental commodity that creates all value.",
    "dayToDayExample": "Spending hours after work cooking dinner, doing laundry, and helping children with homework so the family can function productively every day.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Generalized Commodity Production",
    "pattern": "generalized commodity production|generalised commodity production",
    "definition": "An economic system (capitalism) where almost all goods, services, and even human labor-power are produced as commodities for sale on the market.",
    "misconception": "Any society with markets. Ancient societies had markets for surplus goods, but only under capitalism is production universally oriented around selling commodities.",
    "dayToDayExample": "A society where food, shelter, healthcare, education, and labor are all bought and sold through commercial markets.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Formal Subsumption",
    "pattern": "formal subsumption",
    "definition": "The initial stage of capitalist control where capital takes over an existing labor process (like hand weaving) and places it under a wage contract without yet altering the physical method of work.",
    "misconception": "That capitalism instantly invents new technology. Formal subsumption changes the legal ownership of work before re-engineering the work process.",
    "dayToDayExample": "A merchant buying up artisan workshops and paying artisans wages while they continue using traditional hand tools.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Real Subsumption",
    "pattern": "real subsumption",
    "definition": "The developed stage of capitalist control where the labor process itself is physically transformed through machinery, automation, and assembly lines to maximize surplus value extraction.",
    "misconception": "Just adding technology. Real subsumption fundamentally alters worker habits, pacing, and control over daily tasks.",
    "dayToDayExample": "Replacing independent artisan workshops with a mechanized, computer-timed assembly line.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Absolute Surplus Value",
    "pattern": "absolute surplus value",
    "definition": "Surplus value extracted by extending the overall duration of the working day while keeping necessary labor time constant.",
    "misconception": "That lengthening shifts is the only way bosses profit. Absolute surplus value is one of two key methods, limited physically by human endurance and legal limits.",
    "dayToDayExample": "Increasing factory shift lengths from 8 hours to 10 hours without raising daily base pay.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Relative Surplus Value",
    "pattern": "relative surplus value",
    "definition": "Surplus value extracted by increasing labor productivity through technology and organization, reducing the time needed to produce daily worker subsistence and expanding surplus labor time.",
    "misconception": "That technology automatically lightens worker shifts. Capitalists use relative surplus value to extract more unpaid value within the same shift length.",
    "dayToDayExample": "Introducing automated machinery that halves the time needed to make worker goods, allowing more of the 8-hour shift to generate net profit.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Collectivization",
    "pattern": "collectivization|collectivize|collectivised|collectivizing|collective farming",
    "definition": "The policy of consolidating individual smallholder farmsteads into large-scale, collectively managed agricultural cooperatives (kolkhozes) or state-owned farms (sovkhozes) utilizing modern machinery and shared infrastructure.",
    "misconception": "That collectivization meant seizing personal household items or small family gardens. Collectivization targets agricultural land and heavy farm equipment to transition farming to large-scale social production.",
    "dayToDayExample": "A group of small family farms pooling their land parcels, tractors, and irrigation systems to operate a large shared agricultural cooperative.",
    "theoryTags": ["Marxism-Leninism"]
  },
  {
    "term": "Organic Composition of Capital",
    "pattern": "organic composition of capital",
    "definition": "The ratio of constant capital (machinery and raw materials) to variable capital (wages for labor). As capitalism develops, technological competition raises the organic composition of capital.",
    "misconception": "A biology term. It measures how capital-intensive an enterprise or industry is relative to human labor employment.",
    "dayToDayExample": "An automated semiconductor plant spending $100 million on machines for every $1 million in worker wages.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Rate of Exploitation",
    "pattern": "rate of exploitation|rate of surplus value|rate of surplus-value",
    "definition": "The ratio of surplus value produced by workers to the variable capital paid in wages (s/v), measuring the proportion of unpaid labor extracted relative to paid labor.",
    "misconception": "Measuring how mean a boss is. The rate of exploitation is a numerical ratio of unpaid labor time to paid labor time.",
    "dayToDayExample": "A worker producing $300 in surplus value while being paid $100 in wages, representing a 300% rate of exploitation.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Socially Necessary Labor Time",
    "pattern": "socially necessary labor time|socially necessary labour time",
    "definition": "The average labor time required to produce a commodity under normal conditions of production with average skill and intensity.",
    "misconception": "That a slow worker creates more value by taking longer. If a worker takes 10 hours to make a shoe that normally takes 2 hours, the shoe still only contains 2 hours of value.",
    "dayToDayExample": "The industry standard time of 30 minutes to assemble a smartphone establishing its value, regardless of an individual factory's speed.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Transformation Problem",
    "pattern": "transformation problem",
    "definition": "The economic debate in Marxist economics regarding how values based on labor time convert into actual market prices of production across industries with varying capital compositions.",
    "misconception": "A flaw that disproves labor value. The transformation problem shows how profits equalize across industries while aggregate prices remain bound to aggregate value.",
    "dayToDayExample": "Capital moving from labor-heavy industries to tech-heavy industries until profit rates align, while overall economy-wide prices reflect total labor time.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Concentration of Capital",
    "pattern": "concentration of capital",
    "definition": "The growth of individual capital enterprises over time through the continuous reinvestment of accumulated surplus value (profits).",
    "misconception": "The buyout of competitors. Concentration is internal growth through profit accumulation, whereas centralization is corporate mergers and acquisitions.",
    "dayToDayExample": "A local manufacturer reinvesting annual profits to build larger factory additions year after year.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Centralization of Capital",
    "pattern": "centralization of capital|centralisation of capital",
    "definition": "The combination and takeover of existing capital enterprises through corporate buyouts, mergers, and credit pressure, concentrating control of wealth into fewer hands.",
    "misconception": "That market competition preserves small businesses forever. Competition naturally leads to corporate takeovers and industrial centralization.",
    "dayToDayExample": "A multinational corporation acquiring three rival companies to control 80% of market distribution.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "General Intellect",
    "pattern": "general intellect",
    "definition": "A concept from Marx's Grundrisse referring to the collective scientific knowledge, technological expertise, and social intelligence embodied in machinery and social production.",
    "misconception": "Individual genius. General intellect represents the shared human knowledge base that becomes the primary driver of productivity in advanced technical economies.",
    "dayToDayExample": "Open-source software libraries, scientific research databases, and automated algorithms driving global productivity.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Immiseration",
    "pattern": "immiseration|immiseration of the working class|pauperization",
    "definition": "The structural tendency under capitalism for the relative position of the working class to deteriorate as wealth concentrates in the hands of capital owners.",
    "misconception": "That workers always become completely destitute. Relative immiseration means workers receive a shrinking share of total wealth despite overall productivity growth.",
    "dayToDayExample": "Corporate profits and productivity skyrocketing over decades while real purchasing power for average worker wages stagnates.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Class Reductionism",
    "pattern": "class reductionism|class reductionist|class reductionists",
    "definition": "A mistaken critique or vulgar distortion that reduces all social issues, oppression, and identity struggles solely to economic class, ignoring race, gender, and imperialism.",
    "misconception": "That genuine Marxism ignores special forms of oppression. Traditional Marxism already recognizes how racial, gender, and national oppressions work with and reinforce class rule.",
    "dayToDayExample": "Dismissing anti-racist or feminist campaigns by claiming that class struggles alone will automatically solve all social prejudice.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Economic Determinism",
    "pattern": "economic determinism",
    "definition": "A vulgar reduction of historical materialism claiming that economic factors mechanically dictate every human action, idea, and cultural event without human agency.",
    "misconception": "That Marxism is economic determinism. Marx and Engels explicitly rejected mechanical determinism, emphasizing active class struggle and human agency.",
    "dayToDayExample": "Claiming political election outcomes can be predicted 100% strictly from monthly unemployment figures.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Productivism",
    "pattern": "productivism|productivist",
    "definition": "An ideological commitment to industrial growth and output expansion for their own sake, ignoring ecological sustainability and human liberation.",
    "misconception": "That Marxism prioritizes endless factory output over nature. Marx's ecological writings highlight how capitalism disrupts the metabolic interaction between humanity and earth.",
    "dayToDayExample": "Promoting destructive industrial extraction programs while ignoring environmental degradation and community health.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Strike",
    "pattern": "strike|strikes|striking|strike action",
    "definition": "The collective stoppage of work by employees as a primary weapon of economic and political leverage against capitalist employers to force concessions or challenge state power.",
    "misconception": "A minor economic dispute. For Marxists, a strike is a crucial school of class struggle where workers experience collective power against capital.",
    "dayToDayExample": "Factory workers halting assembly lines and refusing to operate machinery until wage cuts are reversed.",
    "theoryTags": ["Classical Marxism", "Marxism-Leninism"]
  },
  {
    "term": "Trade Union",
    "pattern": "trade union|trade unions|labor union|labour union|unions",
    "definition": "An association of workers formed to collectively bargain with employers over wages, working conditions, and benefits, and to defend worker interests against capitalist exploitation.",
    "misconception": "That trade unions automatically create socialism. Lenin noted that unions fight for better terms within capitalism, requiring revolutionary political leadership to challenge state power.",
    "dayToDayExample": "Hospital nurses organizing a collective bargaining committee to negotiate mandatory nurse-to-patient safety ratios.",
    "theoryTags": ["Classical Marxism", "Marxism-Leninism"]
  },
  {
    "term": "General Strike",
    "pattern": "general strike|general strikes",
    "definition": "A synchronized strike action across multiple key industries and sectors within a region or nation, halting the entire capitalist economy to demand major political or social changes.",
    "misconception": "Just a large trade union dispute. A general strike directly challenges state authority by demonstrating that society cannot function without worker labor.",
    "dayToDayExample": "Transit, factory, dock, and utility workers shutting down operations nationwide to defeat anti-labor legislation.",
    "theoryTags": ["Classical Marxism", "Marxism-Leninism", "Anarcho-Communism"]
  },
  {
    "term": "Marxism",
    "pattern": "marxism|marxist|marxists",
    "definition": "The scientific worldview, materialist philosophy, and economic method formulated by Karl Marx and Friedrich Engels, analyzing class struggle, historical development, and the overthrow of capitalism in favor of a communist society.",
    "misconception": "A rigid dogma or moral opinion. Marxism is a dynamic scientific method (historical and dialectical materialism) for analyzing economic development and class forces.",
    "dayToDayExample": "Analyzing housing price inflation not as personal landlord greed, but as the systematic commodification of shelter under capitalist property relations.",
    "theoryTags": ["Classical Marxism"]
  }, 
  {
    "term": "Critical Race Theory (Materialist)",
    "pattern": "critical race theory (materialist)|materialist crt|materialist critical race theory|marxist crt|racial capitalism",
    "definition": "The materialist branch of Critical Race Theory and Marxist analysis (Derrick Bell, Cedric Robinson, Oliver Cox) asserting that racism is an economic technology created by capitalism to justify colonial plunder, enslavement, land theft, and super-exploitation of minority labor.",
    "misconception": "That racial division is natural or eternal. Materialist CRT demonstrates that racial hierarchies were historically constructed by ruling classes to divide working-class unity and extract superprofits.",
    "dayToDayExample": "Capitalist employers using racial wage differentials and segregated job tiers to prevent white and Black workers from organizing a joint labor union.",
    "theoryTags": ["Classical Marxism", "Anti-Colonial Socialism"]
  },
  {
    "term": "Orthodox Marxism",
    "pattern": "orthodox marxism|orthodox marxist|orthodox marxists",
    "definition": "The theoretical school of Marxism emerging after the death of Marx and Engels (Karl Kautsky, August Bebel, Georgi Plekhanov, Rosa Luxemburg, V.I. Lenin) defending core materialist principles against revisionism, insisting that capitalism cannot be reformed into socialism and must be replaced through working-class revolution.",
    "misconception": "Rigid, unthinking dogmatism. Orthodox Marxism was formed in direct opposition to Eduard Bernstein's reformism, asserting that scientific materialist analysis remains valid and revolutionary.",
    "dayToDayExample": "Insisting that social welfare reforms under capitalism do not alter the fundamental law of surplus-value extraction.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Impossibilism",
    "pattern": "impossibilism|impossibilist|impossibilists",
    "definition": "A revolutionary socialist perspective (associated historically with the Socialist Party of Great Britain and Daniel De Leon) asserting that political action under capitalism should focus exclusively on raising class consciousness to achieve immediate full socialist revolution, rejecting all immediate reform demands ('palliatives') as useless or misleading.",
    "misconception": "Utopian inaction. Impossibilists argue that campaigning for small reforms distracts the working class and bolsters capitalist state legitimacy, whereas Leninists advocate combining immediate reform struggles with revolutionary strategy.",
    "dayToDayExample": "Refusing to campaign for minor wage-tax adjustments, insisting instead on building support for complete social abolition of wage labor.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Industrialization",
    "pattern": "industrialization|industrialize|industrializing|industrialized",
    "definition": "The historical transition from agrarian, handicraft-based economies to mechanized factory production, radically transforming productive forces and creating the modern working class (proletariat).",
    "misconception": "That industrialization under capitalism is a purely neutral technological upgrade for general human welfare. Marxist Critique: Under capitalism, industrialization separates workers from their tools, subjects labor to intense factory discipline, and concentrates ownership in the hands of the bourgeoisie to maximize surplus value extraction; under socialism, industrialization serves to reduce work hours and satisfy human needs.",
    "dayToDayExample": "Replacing manual handloom weaving with steam-powered or electric textile factories, concentrating hundreds of workers into single workplaces under strict shift supervisors.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Automation",
    "pattern": "automation|automate|automated|automating|robotic automation|ai automation",
    "definition": "The substitution of human mental and physical labor with automated machinery, robotics, and computer algorithms in the production process, increasing the organic composition of capital.",
    "misconception": "That automation is inherently bad or causes poverty on its own. Marxist Critique: Automation under capitalism threatens workers with layoffs, wage suppression, and unemployment because technology is deployed for private profit; under socialism, automation is a liberating force that reduces the necessary work week for everyone while maintaining full access to societal goods.",
    "dayToDayExample": "A factory installing automated robotic arms or an office deploying AI software, allowing one worker to monitor output that previously required twenty employees, while corporate management uses the efficiency gains to lay off staff rather than shorten working hours.",
    "theoryTags": ["Classical Marxism", "Neo-Marxism"]
  },
  {
    "term": "Post-Scarcity",
    "pattern": "post-scarcity|post scarcity|postscarcity|post-scarcity society",
    "definition": "A stage of socioeconomic development where advanced productive forces, automation, and communal resource allocation enable society to produce goods and services in sufficient abundance to meet all human basic needs without requiring compulsory wage labor or market pricing.",
    "misconception": "A sci-fi fantasy where every material desire is infinite. Post-scarcity in Marxist theory means reaching a level of technological and social development where essential goods (food, shelter, healthcare, energy, education) are abundant enough to eliminate economic competition and class struggle.",
    "dayToDayExample": "Public municipal utilities providing clean water, electricity, high-speed digital access, and public transit freely to all residents without fee meters or billing statements.",
    "theoryTags": ["Classical Marxism", "Neo-Marxism"]
  },
  {
    "term": "Artificial Scarcity",
    "pattern": "artificial scarcity|artificially scarce|manufactured scarcity",
    "definition": "The deliberate restriction of production, supply, distribution, or access to goods, land, or digital data by capitalists and state entities to inflate prices, enforce market dependency, and guarantee private corporate profit.",
    "misconception": "Natural physical shortages. Under modern capitalism, artificial scarcity is manufactured through patents, paywalls, landlord vacancy hoarding, and agricultural destruction while productive capacity is already fully capable of meeting human need.",
    "dayToDayExample": "Pharmaceutical companies using patent laws to block cheap generic drug manufacturing, or landlords leaving apartment units empty to keep city rental prices artificially high.",
    "theoryTags": ["Classical Marxism", "Capitalist Theory"]
  },
  {
    "term": "Planned Obsolescence",
    "pattern": "planned obsolescence|built-in obsolescence|designed obsolescence",
    "definition": "A capitalist business strategy of deliberately designing products with a limited lifespan, unrepairable parts, or artificial software locks to force consumers to repeatedly purchase replacement goods.",
    "misconception": "Unavoidable wear and tear. Planned obsolescence is an economic mechanism of capital accumulation that wastes natural resources and human labor purely to maintain corporate sales volume.",
    "dayToDayExample": "Smartphone manufacturers releasing software updates that intentionally slow down older models and gluing batteries into devices to prevent easy repair.",
    "theoryTags": ["Capitalist Theory", "Neo-Marxism"]
  }
];


