import type { GlossaryTerm } from './types';

export const postmodernTerms: GlossaryTerm[] = [
  {
    "term": "Deconstruction",
    "pattern": "deconstruction|deconstruct|deconstructing|deconstructive",
    "definition": "A philosophical method formulated by Jacques Derrida analyzing how texts, language, and cultural concepts contain internal contradictions and unstable binary oppositions (such as male/female, nature/culture, center/margin).",
    "misconception": "Simply destroying or criticizing ideas. Marxist Critique: Marxist theorists (such as Alex Callinicos and Terry Eagleton) point out that deconstruction reduces real economic exploitation and state violence to endless textual play, abandoning objective material reality and class struggle.",
    "dayToDayExample": "Analyzing corporate diversity slogans to reveal how they use progressive language while concealing labor wage exploitation.",
    "theoryTags": ["Postmodernism"]
  },
  {
    "term": "Hyperreality / Simulacra",
    "pattern": "hyperreality|simulacra|simulacrum|simulations and simulacra",
    "definition": "Jean Baudrillard's postmodern concepts: a 'simulacrum' is an image or representation without an original reality, creating a state of 'hyperreality' where media symbols and artificial simulations replace real physical experience.",
    "misconception": "That the real world does not exist. Marxist Critique: Fredric Jameson demonstrates that hyperreality is not a mysterious metaphysical state, but the cultural logic of late capitalism, where commodity fetishism and media saturation alienate workers from objective economic production.",
    "dayToDayExample": "Theme parks and digital virtual worlds where visitors experience manufactured symbols that feel more vibrant than physical nature.",
    "theoryTags": ["Postmodernism", "Neo-Marxism"]
  },
  {
    "term": "Metanarrative",
    "pattern": "metanarrative|metanarratives|grand narrative|grand narratives",
    "definition": "Jean-François Lyotard's definition of postmodernism as 'incredulity toward metanarratives', rejecting grand overarching historical stories (such as Christian salvation, Enlightenment progress, or Marxist revolution).",
    "misconception": "A simple critique of dogmatism. Marxist Critique: Lyotard's rejection of metanarratives serves a bourgeois ideological function by attempting to delegitimize historical materialism, preventing the working class from understanding global imperialism and capitalist totality.",
    "dayToDayExample": "Asserting that there is no universal human history or global economic system, only localized micro-stories.",
    "theoryTags": ["Postmodernism"]
  },
  {
    "term": "Discourse",
    "pattern": "discourse|discursive|discursive formation|discursive power",
    "definition": "Michel Foucault's concept explaining how institutional language, knowledge systems, and social practices define what can be spoken, known, and accepted as truth within a given historical epoch.",
    "misconception": "Just words or speeches. Marxist Critique: While Foucaultian discourse highlights institutional language, Marxists emphasize that discourses are not autonomous; they are superstructure phenomena generated by underlying material class relations and state power.",
    "dayToDayExample": "Medical and legal terminology framing poverty as individual mental illness or personal criminality rather than systemic economic deprivation.",
    "theoryTags": ["Postmodernism", "Neo-Marxism"]
  },
  {
    "term": "Biopolitics",
    "pattern": "biopolitics|biopower|biopolitical",
    "definition": "Foucault's concept describing how modern states manage and regulate populations through health statistics, birth rates, hygiene, migration control, and demography rather than direct monarchical execution.",
    "misconception": "Neutral public healthcare management. Marxist Critique: Biopower represents the modern bourgeois state optimizing the physical reproduction of labor-power, regulating human bodies to maximize surplus-value extraction for capital.",
    "dayToDayExample": "State public health campaigns tracking fertility rates, vaccination records, and labor productivity metrics to manage national economic output.",
    "theoryTags": ["Postmodernism", "Neo-Marxism"]
  },
  {
    "term": "Rhizome",
    "pattern": "rhizome|rhizomatic|rhizomatic thinking",
    "definition": "Gilles Deleuze and Félix Guattari's postmodern concept of a decentralized, non-hierarchical network structure that grows horizontally without a single root or central authority, contrasted with hierarchical 'arborescent' tree structures.",
    "misconception": "A purely progressive organizational ideal. Marxist Critique: While rhizomatic networks offer tactical flexibility, Leninists point out that leaderless horizontal networks lack the centralized discipline, scale, and party organization needed to defeat the armed capitalist state.",
    "dayToDayExample": "Decentralized internet open-source communities or leaderless protest networks connecting autonomously across locations.",
    "theoryTags": ["Postmodernism"]
  },
  {
    "term": "Différance",
    "pattern": "differance|différance",
    "definition": "Derrida's pun combining 'deferral' and 'difference', asserting that linguistic meaning is never immediately present in a word, but constantly deferred through endless references to other words.",
    "misconception": "A simple linguistic curiosity. Marxist Critique: Materialists argue that while words defer meaning in text, physical material reality (such as hunger, shelter, and labor exploitation) possesses objective presence that cannot be dissolved by linguistic skepticism.",
    "dayToDayExample": "Looking up a dictionary definition and finding words defined by other words in an endless circular chain.",
    "theoryTags": ["Postmodernism"]
  },
  {
    "term": "Schizoanalysis",
    "pattern": "schizoanalysis|desiring-production|schizoanalytic",
    "definition": "Deleuze and Guattari's critique of Freudian psychoanalysis in 'Anti-Oedipus', arguing that human desire is not a repressed psychological family drama, but a productive force ('desiring-production') shaped by capitalism.",
    "misconception": "Promoting clinical mental illness. Marxist Critique: While Deleuze and Guattari critique bourgeois family norms, Marxists note that celebrating unorganized 'desiring-production' underestimates the necessity of organized class consciousness and state power.",
    "dayToDayExample": "Analyzing how advertising channels human desires into consumer product purchases.",
    "theoryTags": ["Postmodernism"]
  },
  {
    "term": "Panopticism",
    "pattern": "panopticism|panopticon|disciplinary power|surveillance state|foucaultian surveillance",
    "definition": "Michel Foucault's analysis of modern social control (inspired by Jeremy Bentham's Panopticon prison design): power operates not through physical violence, but through continuous surveillance, timetables, and micro-regulations that train individuals to self-regulate.",
    "misconception": "Just prison architecture. Marxist Critique: Marxists emphasize that disciplinary surveillance in factories and workplaces is not an abstract technology of power, but a direct mechanism for enforcing capitalist rate-of-exploitation and extracting surplus value.",
    "dayToDayExample": "Keystroke logging software and surveillance cameras in a call center making employees monitor and speed up their own work performance.",
    "theoryTags": ["Postmodernism", "Neo-Marxism"]
  },
  {
    "term": "Governmentality",
    "pattern": "governmentality|art of government|foucaultian governmentality",
    "definition": "Foucault's term for the historical ensemble of institutions, calculations, and tactics through which modern states govern populations by shaping individual desires, habits, and self-conduct ('the conduct of conduct').",
    "misconception": "Just government regulations. Marxist Critique: Foucaultian governmentality describes neoliberal ideology, where the capitalist state offloads welfare responsibilities onto workers by forcing them to manage themselves as self-exploiting commodities.",
    "dayToDayExample": "Promoting personal credit scores and self-help apps so individuals manage their own financial security rather than demanding state welfare programs.",
    "theoryTags": ["Postmodernism", "Neo-Marxism"]
  },
  {
    "term": "Power-Knowledge",
    "pattern": "power-knowledge|power knowledge|pouvoir-savoir|foucaultian power",
    "definition": "Foucault's concept asserting that power and knowledge are inseparable: power produces legitimate forms of knowledge, and knowledge institutions (criminology, psychiatry, economics) reinforce power relations.",
    "misconception": "That power is everywhere and nowhere in particular. Marxist Critique: Marxists criticize Foucault's power-knowledge for obscuring class dominance, emphasizing that knowledge institutions (academia, media, law) are controlled by the ruling class to serve capitalist hegemony.",
    "dayToDayExample": "Psychiatric diagnostic manuals defining social deviance or protest behavior as individual clinical pathology.",
    "theoryTags": ["Postmodernism", "Neo-Marxism"]
  },
  {
    "term": "Precarity",
    "pattern": "precarity|precariousness|butlerian precarity",
    "definition": "Judith Butler and Post-Marxist concept: 'Precariousness' is an inherent vulnerability of human bodily life, while 'Precarity' is the politically induced condition where specific vulnerable populations suffer from economic instability, social exposure, and lack of state protection under neoliberal capitalism.",
    "misconception": "A new unique identity separate from the working class. Marxist Critique: Marxist economists explain that 'precarity' is not a novel post-industrial phenomenon, but the classic capitalist creation of an industrial reserve army of labor designed to suppress wages.",
    "dayToDayExample": "Gig workers without health insurance or union protections facing injury or job loss without any social safety net.",
    "theoryTags": ["Postmodernism", "Neo-Marxism"]
  }
];
