import React from 'react';
import { HelpCircle, Sparkles, Lightbulb, Tag } from 'lucide-react';

export type TheoryTag = 
  | 'Classical Marxism' 
  | 'Marxism-Leninism' 
  | 'Trotskyism' 
  | 'Maoism';

export interface GlossaryTerm {
  term: string;
  pattern: string; // Pipe-separated regex pattern variants
  definition: string;
  misconception: string;
  dayToDayExample: string;
  theoryTags: TheoryTag[];
}

export const getTermSlug = (term: string): string => {
  return term.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
};

export const glossary: GlossaryTerm[] = [
  {
    "term": "Bourgeoisie",
    "pattern": "bourgeoisie|bourgeois|bourgeoise",
    "definition": "The class of people in society who own the businesses, factories, land, and machinery that generate wealth. They survive by employing workers to run their assets.",
    "misconception": "Anyone who is wealthy or middle-class. In reality, a high-earning office worker is still not part of the bourgeoisie unless they own businesses that generate passive income from other people's work.",
    "dayToDayExample": "A tech billionaire or real estate developer who earns income from the profits generated by employees or tenants, without needing to perform manual shift work.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Proletariat",
    "pattern": "proletariat|proletarians|proletarian",
    "definition": "The modern working class. This includes anyone who must sell their time and ability to work (labor-power) for a wage or salary to survive, because they do not own businesses or land.",
    "misconception": "Only manual laborers or people working in industrial factories. Today, office staff, retail workers, teachers, nurse assistants, and software developers are all part of the proletariat because they survive on wages.",
    "dayToDayExample": "A nurse, teacher, retail worker, or software developer who must sell their time for a paycheck because they do not own a company or land.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Private Property",
    "pattern": "private property",
    "definition": "Productive assets that make money by employing other people's labor (like factories, machinery, office buildings, or rental properties).",
    "misconception": "Your personal belongings (like your clothes, car, phone, or the house you live in). Marxism does not want to take away your personal items: it only wants to end the private ownership of businesses that exploit other people's labor.",
    "dayToDayExample": "A corporate warehouse or apartment complex owned to extract revenue, as opposed to personal belongings like your phone, clothes, or car.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Means of Production",
    "pattern": "means of production",
    "definition": "The physical tools, land, raw materials, and factories required to produce goods and services.",
    "misconception": "The final products themselves (like a phone or a loaf of bread). The means of production are the factories and farms used to make them, which socialists believe should be owned collectively by society rather than by private owners.",
    "dayToDayExample": "The heavy machinery in a car factory or the server farms used by cloud computing platforms to generate commercial products.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Commodity",
    "pattern": "commodity|commodities",
    "definition": "A good or service produced specifically for the purpose of selling it in the market to make a profit, rather than for direct personal use.",
    "misconception": "Any useful object. A coat you sew for yourself is a useful object; it only becomes a commodity when it is manufactured in a factory to be sold in stores.",
    "dayToDayExample": "A coat produced in a factory specifically to be shipped and sold in retail stores for profit.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Commodity Fetishism",
    "pattern": "commodity fetishism|fetishism of commodities",
    "definition": "The illusion under capitalism where social relationships between human beings appear as economic relationships between inanimate objects and money prices.",
    "misconception": "An unhealthy obsession with luxury brands. Commodity fetishism means treating a price tag or product as having inherent magical value, obscuring the human labor and working conditions that created it.",
    "dayToDayExample": "Buying a designer shirt for $150 and viewing it as a symbol of status, while remaining unaware of the factory workers who stitched it.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Labor-Power",
    "pattern": "labor-power|labour-power|labor power|labour power",
    "definition": "A worker's capacity to work: their time, physical energy, and mental focus.",
    "misconception": "The work itself, or the value of the final product. Capitalists do not buy your completed products; they buy your time and energy (labor-power) for a shift, and then they own everything you produce during those hours.",
    "dayToDayExample": "Working an eight-hour shift at a coffee shop, where you trade your physical energy and focus for a fixed hourly wage.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Capital",
    "pattern": "capital",
    "definition": "Wealth (money, equipment, or properties) that is invested to make more wealth through the employment of wage labor.",
    "misconception": "Just savings or cash. Money only becomes capital when it is actively used to buy assets and hire workers to generate profit.",
    "dayToDayExample": "An investor purchasing fleet vehicles and equipment to hire workers and launch a profit-generating logistics business.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Class Struggle",
    "pattern": "class struggle|class struggles",
    "definition": "The built-in conflict of interest between those who own the businesses and those who work for them.",
    "misconception": "Personal hatred or violent riots. Class struggle is an objective economic reality: employers naturally want to keep wages low and hours high to increase profits, while workers want higher wages and shorter hours.",
    "dayToDayExample": "Warehouse workers bargaining for safer working conditions and higher wages while management seeks to cut operating costs.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Surplus Value",
    "pattern": "surplus value|surplus-value",
    "definition": "The extra value created by workers above the cost of their own wages. This unpaid labor is the source of all capitalist profit.",
    "misconception": "Just the markup price of a commodity. It is actually the difference between the total value the worker produces and the wage they receive.",
    "dayToDayExample": "A worker creating $200 worth of merchandise during a shift while receiving $20 an hour in wages, leaving the remaining profit with the business owner.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Exploitation",
    "pattern": "exploitation|exploited|exploits",
    "definition": "The process where capitalists extract surplus value from the unpaid labor of workers, paying them less than the value they produce.",
    "misconception": "Only occurring under extremely bad working conditions or abusive bosses. For Marxists, exploitation is an objective, mathematical reality of all wage labor: even well-paid software developers are exploited if they produce more value than their salary.",
    "dayToDayExample": "A software developer earning a fixed annual salary while their code generates millions of dollars in recurring subscription profits for company shareholders.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Alienation",
    "pattern": "alienation|alienated",
    "definition": "The feeling of separation and lack of control that workers experience under capitalism: separation from the product of their labor, from the act of production, from their fellow workers, and from their human potential.",
    "misconception": "Simply feeling lonely or sad. It is an objective condition caused by workers having no control over their daily labor or what happens to the products they make.",
    "dayToDayExample": "An assembly line worker who installs car doors all day but cannot afford to purchase the car they help build, feeling disconnected from their daily labor.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Use-Value",
    "pattern": "use-value|use value|use-values|use values",
    "definition": "The practical utility of a commodity: how it satisfies a human need or desire (like a coat keeping you warm).",
    "misconception": "The price of an item. Use-value is qualitative, while price or exchange-value is quantitative. A glass of water has immense use-value for survival but usually has very little exchange-value.",
    "dayToDayExample": "A warm winter jacket keeping you dry and insulated during cold weather.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Exchange-Value",
    "pattern": "exchange-value|exchange value|exchange-values|exchange values",
    "definition": "The proportion in which a commodity exchanges for other commodities, which under capitalism is expressed as a money price.",
    "misconception": "The same as use-value. An object can have high use-value but no exchange-value (like air or home-cooked meals), or high exchange-value but little use-value (like a diamond).",
    "dayToDayExample": "A smartphone listed in a store for $999 or traded for three months of grocery purchases.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Class Interest",
    "pattern": "class interest|class interests",
    "definition": "The shared economic and political goals that arise from a group's position in the system of production. The bourgeoisie's class interest is to maximize profits and protect private property; the proletariat's class interest is to improve wages, conditions, and ultimately to collectively own the means of production.",
    "misconception": "Individual personal preferences or opinions. Class interest is not about what a single person wants; it is the objective set of economic goals that benefit an entire class, whether or not individual members are aware of them.",
    "dayToDayExample": "Workers pushing for strong public healthcare funded by corporate taxes, while corporate leaders lobby for tax reductions to boost dividends.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Finance Capital",
    "pattern": "finance capital|financial capital",
    "definition": "The fusion of banking capital with industrial monopoly capital under the direction of powerful financial magnates and mega-banks.",
    "misconception": "Just any money spent on investments. Finance capital is specifically the stage of capitalism where banks and financial institutions direct and control industrial monopolies.",
    "dayToDayExample": "A major investment firm acquiring controlling ownership of healthcare chains and manufacturing companies to guide corporate operations from Wall Street.",
    "theoryTags": ["Marxism-Leninism"]
  },
  {
    "term": "Imperialism",
    "pattern": "imperialism|imperialist|imperialists",
    "definition": "The highest stage of capitalism, characterized by monopolies, finance capital dominance, export of capital to developing nations, and global geopolitical division.",
    "misconception": "Simply any foreign military invasion. For Marxists, imperialism is an economic stage where dominant capitalist countries export capital and extract raw materials and superprofits from developing countries.",
    "dayToDayExample": "Multinational conglomerates securing exclusive mineral rights in developing nations to supply battery factories in wealthier nations.",
    "theoryTags": ["Marxism-Leninism"]
  },
  {
    "term": "Monopoly & Monopoly Capital",
    "pattern": "monopoly|monopolies|monopoly capital|monopolistic",
    "definition": "A market situation where giant corporate combines control entire industries, restricting competition, fixing prices, and earning superprofits.",
    "misconception": "That capitalism is always defined by free competition among small businesses. Capitalism naturally leads to concentration of production into mega-monopolies over time.",
    "dayToDayExample": "A single internet service provider being the only choice in a city, enabling them to raise prices without fear of losing customers.",
    "theoryTags": ["Marxism-Leninism"]
  },
  {
    "term": "Capitalism & Capitalist",
    "pattern": "capitalism|capitalist|capitalists|capitalistic",
    "definition": "An economic system where the means of production (factories, land, technology) are privately owned by capitalists, and production is driven by profit using paid wage labor.",
    "misconception": "That capitalism simply means trade or buying goods in a market. Markets existed for thousands of years before capitalism; capitalism specifically refers to a system dominated by private corporate ownership and wage labor.",
    "dayToDayExample": "Working at a privately held corporation where executives and shareholders decide how profits are allocated while employees receive fixed salaries.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Communism & Communist",
    "pattern": "communism|communist|communists|communist party",
    "definition": "A stateless, classless, moneyless socio-economic system where the means of production are owned collectively by society to satisfy human needs rather than generate private corporate profit.",
    "misconception": "That communism means total state control over your personal life and belongings. In Marxist theory, communism represents the ultimate stage of social development where the state has withered away and workers democratically control social wealth.",
    "dayToDayExample": "A public library system where resources are shared freely based on need, expanded to cover all essential goods and services in society.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Socialism & Socialist",
    "pattern": "socialism|socialist|socialists|socialistic",
    "definition": "The transitional economic system following capitalism, where the working class holds political power and collectively owns the means of production to organize society according to human needs.",
    "misconception": "Just government welfare programs or high taxes in a capitalist country. True socialism requires replacing private corporate ownership of major industries with democratic public ownership by working people.",
    "dayToDayExample": "A community-owned electrical utility governed democratically by workers and residents, providing power at cost rather than marking up prices for corporate profit.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Feudalism & Serfdom",
    "pattern": "feudalism|feudal|feudalist|feudal lords|serf|serfs|serfdom",
    "definition": "The medieval economic system preceding capitalism, where landowning lords controlled society and peasant serfs were legally bound to work the land in exchange for a portion of the crops.",
    "misconception": "That feudalism was identical to modern capitalism. Under feudalism, exploitative relations were transparent and enforced by physical obligation and legal status, whereas under capitalism they are mediated by wage contracts.",
    "dayToDayExample": "A medieval peasant surrendering a portion of their grain harvest to a local lord under threat of knightly enforcement to live on the land.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Materialism",
    "pattern": "materialism|materialist|materialists",
    "definition": "The philosophical viewpoint that the physical, material world exists objectively and forms the fundamental basis of all reality, human thoughts, ideas, and social institutions.",
    "misconception": "Being obsessed with buying luxury products or money. In philosophy, materialism means recognizing that physical reality shapes human consciousness, not the other way around.",
    "dayToDayExample": "Understanding that family stress is driven by real economic realities like rent increases and low wages, rather than just bad attitudes.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Dialectics",
    "pattern": "dialectical|dialectics|dialectic",
    "definition": "A method of analysis that views the world as interconnected, constantly changing, and driven forward by internal contradictions and opposing forces.",
    "misconception": "Just debating or arguing with words. Dialectics is a science of real-world development, demonstrating how gradual quantitative changes accumulate until they trigger sudden qualitative shifts.",
    "dayToDayExample": "Water heating up degree by degree (quantitative change) until it suddenly boils into steam (qualitative transformation).",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Dialectical Materialism",
    "pattern": "dialectical materialism",
    "definition": "The core philosophical worldview of Marxism, combining materialist reality (the physical economic world comes first) with dialectics (everything is constantly evolving through internal contradictions).",
    "misconception": "A rigid set of dogma rules. It is actually a dynamic analytical tool that requires studying concrete, changing facts in the real world rather than abstract ideals.",
    "dayToDayExample": "Analyzing how technological automation (material force) creates tension with traditional job structures, driving modern workplace transformations.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Historical Materialism",
    "pattern": "historical materialism",
    "definition": "The application of dialectical materialism to human history: the principle that economic production and class structure form the foundation for all politics, laws, and culture.",
    "misconception": "That human history is driven primarily by great leaders, religious ideas, or speeches. Historical materialism proves that economic transformations drive political and cultural evolution.",
    "dayToDayExample": "Understanding that the rise of the internet reshaped laws, media, and culture because the economic mode of communication changed.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Contradiction",
    "pattern": "contradiction|contradictions",
    "definition": "An inherent tension or conflict between opposing forces within a system (such as the opposing interests of capital and labor) that propels economic and social development.",
    "misconception": "A logical error or mistake in a argument. In Marxist philosophy, a contradiction is an objective, real opposition between material forces in society.",
    "dayToDayExample": "A company needing workers to buy its products to make profits, yet constantly cutting worker pay to lower expenses.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Unity of Opposites",
    "pattern": "unity of opposites|unity of the opposites",
    "definition": "The core law of materialist dialectics stating that every object, concept, or society is composed of contradictory, mutually dependent forces that struggle against each other and drive change.",
    "misconception": "A compromise or peaceful middle ground between two sides. The unity of opposites means that opposing forces exist together in the same entity and cannot exist without each other (like workers and employers), but their inherent conflict pushes the system to evolve.",
    "dayToDayExample": "A ride-hailing app platform and its drivers: drivers need the app to find passengers, and the app needs drivers to operate, yet their financial interests remain in constant tension.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Metaphysics",
    "pattern": "metaphysics|metaphysical|metaphysicians",
    "definition": "A static way of viewing the world as isolated, fixed, and unchanging, ignoring internal forces of development and treating things as separate from their context.",
    "misconception": "Supernatural magic or spiritual mysticism. In Marxist philosophy, metaphysics refers specifically to a non-dialectical mindset that views things in isolation and assumes human nature or society never fundamentally changes.",
    "dayToDayExample": "Assuming that economic inequality is an unchangeable law of human nature that has always existed and will never change.",
    "theoryTags": ["Classical Marxism"]
  },
  {
    "term": "Principal Contradiction",
    "pattern": "principal contradiction|principal contradictions|principal aspect",
    "definition": "In a complex situation containing many conflicts, the single primary contradiction whose existence and development determines or influences all other secondary contradictions.",
    "misconception": "The only conflict that matters. Identifying the principal contradiction means prioritizing the main driving force of a situation without ignoring secondary issues.",
    "dayToDayExample": "During an emergency flood, a city putting aside internal political debates to focus entirely on reinforcing levies and rescuing residents.",
    "theoryTags": ["Maoism"]
  },
  {
    "term": "Antagonistic Contradiction",
    "pattern": "antagonistic contradiction|antagonistic contradictions|antagonism|antagonisms",
    "definition": "A contradiction where the interests of the opposing sides are fundamentally incompatible and can only be resolved through struggle and the transformation or defeat of one side.",
    "misconception": "Personal hostility or anger. Antagonism refers to structural economic and political incompatibility between forces, not personal feelings.",
    "dayToDayExample": "A landlord filing an eviction against a tenant to re-rent the apartment at double the price, where one side winning directly forces the other side to lose.",
    "theoryTags": ["Maoism", "Marxism-Leninism"]
  }
];

// Helper interface for individual variant matching
interface VariantMatch {
  variant: string;
  term: GlossaryTerm;
}

// Flatten all pattern variants into a sorted list by length descending so longer phrases match first
const allVariants: VariantMatch[] = [];
glossary.forEach(item => {
  const variants = item.pattern.split('|');
  variants.forEach(v => {
    const trimmed = v.trim();
    if (trimmed) {
      allVariants.push({ variant: trimmed, term: item });
    }
  });
});
// Sort variants by string length descending
allVariants.sort((a, b) => b.variant.length - a.variant.length);

// Escape regex special characters helper
function escapeRegex(str: string): string {
  return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

// Pre-build regex string with longest variants first
const patternString = allVariants.map(v => escapeRegex(v.variant)).join('|');
const jargonRegex = new RegExp(`\\b(${patternString})\\b`, 'gi');

// Highlight utility
export const highlightJargon = (text: string): React.ReactNode[] => {
  if (!text) return [];

  const parts = text.split(jargonRegex);
  if (parts.length <= 1) {
    return [text];
  }

  return parts.map((part, index) => {
    if (!part) return null;

    const lowerPart = part.toLowerCase();
    // Find matching variant (longest first guaranteed by allVariants sorting)
    const matchedVariant = allVariants.find(v => v.variant.toLowerCase() === lowerPart);

    if (matchedVariant) {
      const matchingTerm = matchedVariant.term;
      const termSlug = getTermSlug(matchingTerm.term);
      return (
        <span 
          key={index} 
          className="jargon-highlight"
          onClick={(e) => {
            e.stopPropagation();
            e.preventDefault();
            const targetHash = `#term-${termSlug}`;
            window.location.hash = targetHash;
            window.dispatchEvent(new CustomEvent('navigate-to-glossary', { detail: { slug: termSlug } }));
          }}
          onMouseEnter={(e) => {
            const rect = e.currentTarget.getBoundingClientRect();
            const balloon = e.currentTarget.querySelector('.tooltip-balloon');
            if (balloon) {
              if (rect.top < 210) {
                balloon.classList.add('pop-down');
              } else {
                balloon.classList.remove('pop-down');
              }
            }
          }}
        >
          {part}
          <span className="tooltip-balloon jargon-tooltip glass-panel">
            <span className="tooltip-balloon-label">
              <Sparkles className="section-icon text-gold" /> Glossary: {matchingTerm.term}
            </span>

            {matchingTerm.theoryTags && matchingTerm.theoryTags.length > 0 && (
              <div className="tooltip-theory-tags">
                {matchingTerm.theoryTags.map((tag) => (
                  <span key={tag} className="theory-tag-pill mini">
                    <Tag className="tag-icon" /> {tag}
                  </span>
                ))}
              </div>
            )}

            <p className="jargon-def-text">{matchingTerm.definition}</p>

            <span className="jargon-example-label">
              <Lightbulb className="section-icon text-amber" /> Day-to-day Example
            </span>
            <p className="jargon-example-text">{matchingTerm.dayToDayExample}</p>

            <span className="jargon-misconception-label">
              <HelpCircle className="section-icon text-crimson" /> Common Misconception
            </span>
            <p className="jargon-misconception-text">{matchingTerm.misconception}</p>
          </span>
        </span>
      );
    }

    return part;
  }).filter(Boolean) as React.ReactNode[];
};
